"""
render.py — emit the dashboard's data file (comp-data.js).

The dashboard front end is a static Broadsheet/React app (index.html + support.js +
_ds/ + the fonts) committed once. Each scan only regenerates this one small data
file, which the page loads via <script src="comp-data.js">:

    window.COMP_DATA   = { generated_utc, last_mode, competitions[], source_health[], ... }
    window.COMP_CONSTS = { redHours, amberHours, chipHours, smartConfigured, models[] }

No HTML is built here anymore. The React app renders everything client-side and
escapes all scraped text by default (safe), so there is no inline-JSON breakout risk.
"""
from __future__ import annotations

import json


def _consts(data: dict, cfg: dict) -> dict:
    th = cfg.get("thresholds", {})
    return {
        "redHours": th.get("ending_soon_hours", 24),
        "amberHours": th.get("amber_hours", 72),
        "chipHours": th.get("ending_chip_hours", 48),
        "smartConfigured": bool(data.get("smart_configured", False)),
        "models": [
            {"id": "haiku", "label": "Haiku (~$0.05–0.15/scan)"},
            {"id": "sonnet", "label": "Sonnet (~$0.30–0.80/scan, smarter)"},
        ],
    }


def data_js(data: dict, cfg: dict) -> str:
    """Return the JavaScript that defines window.COMP_DATA and window.COMP_CONSTS."""
    payload = json.dumps(data, ensure_ascii=False)
    consts = json.dumps(_consts(data, cfg), ensure_ascii=False)
    return (
        "// Auto-generated by scanner.py — the dashboard reads these globals.\n"
        f"window.COMP_DATA = {payload};\n"
        f"window.COMP_CONSTS = {consts};\n"
    )


# Back-compat alias: older callers used render.render(); it now returns the data JS.
def render(data: dict, cfg: dict) -> str:
    return data_js(data, cfg)
